# Generated by Django 5.2.1 on 2025-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_id",
            field=models.CharField(
                default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                editable=False,
                max_length=64,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
