# Generated by Django 5.2.1 on 2025-05-28 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0003_chatmessage_id_alter_chatmessage_message_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="timestamp",
        ),
    ]
