# Generated by Django 5.2.1 on 2025-05-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0007_alter_chatmessage_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="id",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_id",
            field=models.CharField(
                default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
