# Generated by Django 5.2.1 on 2025-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0006_chatmessage_timestamp_chatsession_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name='metadata',
            field=models.TextField(null=True),
        ),
    ]
