# Generated by Django 5.2.1 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0009_chatmessage_id_alter_chatmessage_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="metadata",
            field=models.JSONField(null=True),
        ),
    ]
