# Generated by Django 5.2.1 on 2025-06-03 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0011_alter_chatmessage_id_alter_chatmessage_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="timestamp",
        ),
    ]
