# Generated by Django 5.2.1 on 2025-05-28 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0004_remove_chatmessage_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="timestamp",
        ),
    ]
