# Generated by Django 5.2.1 on 2025-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0013_chatmessage_timestamp_chatsession_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
