# Generated by Django 5.2.1 on 2025-05-29 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0005_remove_chatsession_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name='timestamp',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatsession",
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True,default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
