# Generated by Django 5.2.1 on 2025-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0010_alter_chatmessage_id_alter_chatmessage_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="metadata",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="metadata",
            field=models.TextField(null=True),
        ),
    ]
